
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'app.html'),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els={};
function element(id) { const classes=new Set(); const e={value:'',textContent:'',disabled:false,open:false,isConnected:true,handlers:{},dataset:{},selectedOptions:[{textContent:'Fees & payments'}],classList:{toggle(c,on){on?classes.add(c):classes.delete(c)},contains:c=>classes.has(c),add:c=>classes.add(c),remove:c=>classes.delete(c)},addEventListener(t,fn){(this.handlers[t] ||= []).push(fn)},focus(){},showModal(){this.open=true},close(){this.open=false},checkValidity(){return true},reportValidity(){return true},reset(){},querySelector(){return null}};let inner='';Object.defineProperty(e,'innerHTML',{get:()=>inner,set(s){inner=s;if(id==='requestFields')for(const m of s.matchAll(/id="(request_[^"]+)"/g))els[m[1]]=element(m[1]);if(id==='issueType')e.value=''}});return e; }
ids.forEach(id=>els[id]=element(id));
els.staffForm.querySelector=()=>element("staffSubmit");
const profiles=[{id:'it1',full_name:'IT Staff',role:'staff',department:'it'},{id:'finance1',full_name:'Finance Staff',role:'staff',department:'finance'},{id:'admin1',full_name:'Administrator',role:'admin',department:null}];
const rows=[{id:1,subject:'IT request',description:'Original',category:'Account',department:'it',student_id:'s1',status:'Open',created_at:'2026-01-01',assigned_to:null},{id:2,subject:'Finance request',description:'Original',category:'Other',department:'finance',student_id:'s2',status:'Open',created_at:'2026-01-02',assigned_to:null}];
let failProfileUpdate=false;const calls=[];function query(table){const call={table,filters:[]};calls.push(call);const q={select(){return q},eq(k,v){call.filters.push([k,v]);return q},in(){return q},order(){return q},insert(p){call.insert=p;return q},update(p){call.update=p;return q},then(resolve,reject){return Promise.resolve({data:table==='profiles'?profiles:table==='tickets'?rows:[],error:failProfileUpdate&&call.update?{message:"Test save error"}:null}).then(resolve,reject)}};return q;}
const client={functions:{invoke:async(name,options)=>{calls.push({function:name,body:options.body});return {data:{id:"new-staff"},error:null}}},from:query,auth:{getSession:async()=>({data:{}}),signUp:async()=>({data:{user:{id:'new-staff'}},error:null})}};
const ctx={document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[],activeElement:{focus(){},isConnected:true}},window:{supabase:{createClient:()=>client}},console,alert(){},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
(async()=>{
run('currentUser={id:"it1",role:"staff",department:"it",email:"it@example.com"};');await run('loadTickets()');assert(els.ticketTable.innerHTML.includes('IT request'));assert(!els.ticketTable.innerHTML.includes('Finance request'));assert(calls.at(-1).filters.some(([k,v])=>k==='department'&&v==='it'));assert.equal(run('canReadTicket({department:"finance"})'),false);assert.equal(run('canManageTicket({status:"Open",department:"it",assigned_to:"other"})'),false);assert.equal(run('canManageTicket({status:"Open",department:"it",assigned_to:null})'),true);
run('currentUser.department=null');await run('loadTickets()');assert.equal(run('tickets.length'),0);
run('currentUser={id:"admin1",role:"admin",department:null};');els.detailDepartment.value='it';await run('loadStaffList()');assert(els.detailAssignee.innerHTML.includes('IT Staff'));assert(!els.detailAssignee.innerHTML.includes('Finance Staff'));els.detailDepartment.value='finance';els.detailDepartment.handlers.change[0]();assert(els.detailAssignee.innerHTML.includes('Finance Staff'));assert(!els.detailAssignee.innerHTML.includes('IT Staff'));await run('loadUsers()');assert(els.userTable.innerHTML.includes('data-profile-department'));assert(els.userTable.innerHTML.includes('Finance / Cashier'));
els.staffRole.value='admin';run('syncStaffDepartment()');assert(els.staffDepartment.disabled);assert(!els.staffDepartment.required);els.staffRole.value='staff';run('syncStaffDepartment()');assert(els.staffDepartment.required);
run('currentUser={id:"s1",role:"student",email:"personal@example.com"};');els.supportArea.value='fees';run('resetIssueChoices()');els.issueType.value='Payment is not showing in my account';run('renderRequestFields()');els.subject.value='Missing payment';els.description.value='Payment details';els.request_paymentDate.value='2026-10-01';els.request_reference.value='REF123';await els.ticketForm.handlers.submit[0]({preventDefault(){}});const insert=calls.findLast(c=>c.table==='tickets'&&c.insert).insert;assert.equal(insert.support_area,'fees');assert.equal(insert.concern,'Payment is not showing in my account');assert(!('department' in insert));assert.equal(insert.category,'Other');
run('currentUser={id:"admin1",role:"admin",department:null}');els.staffName.value='New Staff';els.staffEmail.value='staff@example.com';els.staffPass.value='testpassword';els.staffRole.value='staff';els.staffDepartment.value='registrar';await els.staffForm.handlers.submit[0]({preventDefault(){},target:{reset(){}}});const updated=calls.findLast(c=>c.function==='create-staff-account').body;assert.equal(updated.role,'staff');assert.equal(updated.department,'registrar');
run('currentUser={id:"admin1",role:"admin"}');await run('loadUsers()');assert(els.userTable.innerHTML.includes('data-profile-role'));assert(!els.userTable.innerHTML.includes('data-promote-staff'));assert(els.userTable.innerHTML.includes('user-save-status'));assert(!els.userTable.innerHTML.includes('data-save-profile'));run('userDirectory=[{id:"student1",full_name:"Student",role:"student"}];renderUsers()');assert(!els.userTable.innerHTML.includes('data-profile-role'));await run('loadUsers()');els.userRoleFilter.value='staff';run('renderUsers()');assert(!els.userTable.innerHTML.includes('Administrator'));els.userSearch.value='Finance';run('renderUsers()');assert(els.userTable.innerHTML.includes('Finance Staff'));assert(!els.userTable.innerHTML.includes('IT Staff'));assert.equal(run('canManageTicket({status:"Resolved",department:"it"})'),false);run('openTicketDetails({id:3,status:"Resolved",department:"it",subject:"Old",category:"Account",description:"Done"})');assert(els.updateCard.classList.contains('hidden'));assert(els.commentForm.classList.contains('hidden'));
els.userRoleFilter.value='';els.userSearch.value='';await run('loadUsers()');const roleInput={value:'staff'},departmentInput={value:'registrar'},saveStatus={textContent:''};const row={dataset:{profile:'it1'},querySelector:s=>s==='[data-profile-role]'?roleInput:s==='[data-profile-department]'?departmentInput:saveStatus};departmentInput.matches=()=>true;departmentInput.closest=()=>row;await els.userTable.handlers.change[0]({target:departmentInput});assert.equal(saveStatus.textContent,'Department saved');assert.equal(calls.findLast(c=>c.table==='profiles'&&c.update).update.department,'registrar');departmentInput.value='finance';failProfileUpdate=true;await els.userTable.handlers.change[0]({target:departmentInput});assert.equal(departmentInput.value,'registrar');assert(saveStatus.textContent.includes('Could not save'));failProfileUpdate=false;roleInput.value='admin';roleInput.matches=()=>true;roleInput.closest=()=>row;ctx.confirm=()=>false;await els.userTable.handlers.change[0]({target:roleInput});assert.equal(roleInput.value,'staff');
console.log('PASS: department queues, authorization helpers, assignment filtering, admin user controls, staff creation, and routed ticket payloads.');
})().catch(e=>{console.error(e);process.exitCode=1});
