
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'app.html'),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els={};
function element(id) { const classes=new Set(); const e={value:'',textContent:'',disabled:false,open:false,isConnected:true,handlers:{},dataset:{},selectedOptions:[{textContent:'Fees & payments'}],classList:{toggle(c,on){on?classes.add(c):classes.delete(c)},contains:c=>classes.has(c),add:c=>classes.add(c),remove:c=>classes.delete(c)},addEventListener(t,fn){(this.handlers[t] ||= []).push(fn)},focus(){},showModal(){this.open=true},close(){this.open=false},checkValidity(){return true},reportValidity(){return true},reset(){},querySelectorAll(){return []},querySelector(){return null}};let inner='';Object.defineProperty(e,'innerHTML',{get:()=>inner,set(s){inner=s;if(id==='requestFields')for(const m of s.matchAll(/id="(request_[^"]+)"/g))els[m[1]]=element(m[1]);if(id==='issueType')e.value=''}});return e; }
ids.forEach(id=>els[id]=element(id));
els.staffForm.querySelector=()=>element("staffSubmit");
const profiles=[{id:'it1',full_name:'IT Staff',role:'staff',department:'it'},{id:'finance1',full_name:'Finance Staff',role:'staff',department:'finance'},{id:'admin1',full_name:'Administrator',role:'admin',department:null}];
const rows=[{id:1,subject:'IT request',description:'Original',category:'Account',department:'it',student_id:'s1',status:'Open',created_at:'2026-01-01',assigned_to:null},{id:2,subject:'Finance request',description:'Original',category:'Other',department:'finance',student_id:'s2',status:'Open',created_at:'2026-01-02',assigned_to:null}];
let failProfileUpdate=false; let articleFailure=false; let conflict=false; const articles=[{id:"published1",title:"Public help",topic:"account",concern:"Forgot my school account password",steps:["Try recovery"],contact_guidance:"Contact support",status:"published",revision:1,updated_at:"2026-10-03",editor:{full_name:"Admin"}},{id:"draft1",title:"Private draft",topic:"account",steps:[],contact_guidance:"",status:"draft",revision:1,updated_at:"2026-10-03"}];const calls=[];function query(table){const call={table,filters:[]};calls.push(call);const q={select(){return q},eq(k,v){call.filters.push([k,v]);return q},in(){return q},order(){return q},insert(p){call.insert=p;return q},update(p){call.update=p;return q},then(resolve,reject){return Promise.resolve({data:table==='profiles'?profiles:table==='tickets'?rows:table==='help_articles'?(conflict&&call.update?[]:articles.filter(a=>call.filters.every(([k,v])=>a[k]===v))):[],error:(articleFailure&&table==="help_articles")||failProfileUpdate&&call.update?{message:"Test save error"}:null}).then(resolve,reject)}};return q;}
const client={functions:{invoke:async(name,options)=>{calls.push({function:name,body:options.body});return {data:{id:"new-staff"},error:null}}},from:query,auth:{getSession:async()=>({data:{}}),signUp:async()=>({data:{user:{id:'new-staff'}},error:null})}};
const ctx={document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[],activeElement:{focus(){},isConnected:true}},window:{supabase:{createClient:()=>client}},console,alert(){},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
(async()=>{
run('currentUser={id:"student1",role:"student"}');await run('loadHelpArticles()');assert(els.homeFaqs.innerHTML.includes('Public help'));assert(!els.homeFaqs.innerHTML.includes('Private draft'));assert(calls.at(-1).filters.some(([k,v])=>k==='status'&&v==='published'));run('openArticleEditor()');assert.equal(els.articleDialog.open,false);
run('currentUser={id:"it1",role:"staff"}');await run('loadHelpArticles()');assert(els.newArticleBtn.classList.contains('hidden'));assert(!els.knowledgeContent.innerHTML.includes('Private draft'));
run('currentUser={id:"admin1",role:"admin"}');await run('loadHelpArticles()');assert(els.knowledgeContent.innerHTML.includes('Private draft'));assert(!els.newArticleBtn.classList.contains('hidden'));els.knowledgeStatus.value='draft';run('renderKnowledge()');assert(!els.knowledgeContent.innerHTML.includes('Public help'));els.knowledgeStatus.value='';
run('openArticleEditor("published1")');assert.equal(els.articleTitle.value,'Public help');assert.equal(els.articleSteps.value,'Try recovery');els.articleTitle.value='Changed';ctx.confirm=()=>false;run('closeArticleEditor()');assert(els.articleDialog.open);ctx.confirm=()=>true;run('closeArticleEditor()');assert(!els.articleDialog.open);
run('openArticleEditor()');els.articleTitle.value='New help';els.articleTopic.value='account';els.articleConcern.value='';els.articleSteps.value='';els.articleContact.value='';const submit=status=>els.articleForm.handlers.submit[0]({preventDefault(){},submitter:{dataset:{articleSave:status}}});await submit('published');assert(els.articleError.textContent.includes('at least one instruction'));await submit('draft');let saved=calls.findLast(c=>c.table==='help_articles'&&c.insert);assert.equal(saved.insert.status,'draft');assert.equal(saved.insert.concern,null);
run('openArticleEditor("published1")');els.articleSteps.value='First step\n\nSecond step';await submit('published');saved=calls.findLast(c=>c.table==='help_articles'&&c.update);assert.deepEqual(JSON.parse(JSON.stringify(saved.update.steps)),['First step','Second step']);assert(saved.filters.some(([k,v])=>k==='revision'&&v===1));
run('openArticleEditor("published1")');articleFailure=true;await submit('draft');assert(els.articleDialog.open);assert(els.articleError.textContent.includes('Could not save'));assert.equal(run('articleSaving'),false);articleFailure=false;conflict=true;await submit('draft');assert(els.articleError.textContent.includes('changed since'));conflict=false;
articleFailure=true;await run('loadHelpArticles()');assert(els.homeFaqs.innerHTML.includes('Could not load'));articleFailure=false;
run('currentUser={id:"student1",role:"student"}');await run('loadHelpArticles()');const button={dataset:{faqTicket:'published1'}};await els.homeFaqs.handlers.click[0]({target:{closest:s=>s==='[data-faq-ticket]'?button:null}});assert.equal(els.supportArea.value,'account');assert.equal(els.issueType.value,'Forgot my school account password');assert(els.ticketDialog.open);
console.log('PASS: published-only reading, admin editor, filters, draft/publish validation, optimistic concurrency, error recovery, and article-to-ticket concern selection.');
})().catch(e=>{console.error(e);process.exitCode=1});
