
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'app.html'),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els={};
function element(id) { const classes=new Set(); const e={value:'',textContent:'',disabled:false,open:false,isConnected:true,handlers:{},dataset:{},selectedOptions:[{textContent:'Fees & payments'}],classList:{toggle(c,on){on?classes.add(c):classes.delete(c)},contains:c=>classes.has(c),add:c=>classes.add(c),remove:c=>classes.delete(c)},addEventListener(t,fn){(this.handlers[t] ||= []).push(fn)},focus(){},showModal(){this.open=true},close(){this.open=false},checkValidity(){return true},reportValidity(){return true},reset(){},querySelector(){return null}};let inner='';Object.defineProperty(e,'innerHTML',{get:()=>inner,set(s){inner=s;if(id==='requestFields')for(const m of s.matchAll(/id="(request_[^"]+)"/g))els[m[1]]=element(m[1]);if(id==='issueType')e.value=''}});return e; }
ids.forEach(id=>els[id]=element(id));
els.staffForm.querySelector=()=>element("staffSubmit");
const profiles=[{id:'it1',full_name:'IT Staff',role:'staff',department:'it'},{id:'finance1',full_name:'Finance Staff',role:'staff',department:'finance'},{id:'admin1',full_name:'Administrator',role:'admin',department:null}];
const rows=[{id:1,subject:'IT request',description:'Original',category:'Account',department:'it',student_id:'s1',status:'Open',created_at:'2026-01-01',assigned_to:null},{id:2,subject:'Finance request',description:'Original',category:'Other',department:'finance',student_id:'s2',status:'Open',created_at:'2026-01-02',assigned_to:null}];
let failProfileUpdate=false;const calls=[];function query(table){const call={table,filters:[]};calls.push(call);const q={select(){return q},eq(k,v){call.filters.push([k,v]);return q},in(){return q},order(){return q},insert(p){call.insert=p;return q},update(p){call.update=p;return q},then(resolve,reject){return Promise.resolve({data:table==='profiles'?profiles:table==='tickets'?rows:[],error:failProfileUpdate&&call.update?{message:"Test save error"}:null}).then(resolve,reject)}};return q;}
let authListener;const client={functions:{invoke:async(name,options)=>{calls.push({function:name,body:options.body});return {data:{id:"new-staff"},error:null}}},from:query,auth:{onAuthStateChange:fn=>{authListener=fn;return {data:{subscription:{unsubscribe(){}}}}},getSession:async()=>({data:{}}),signUp:async()=>({data:{user:{id:'new-staff'}},error:null})}};
const ctx={document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[],activeElement:{focus(){},isConnected:true}},URL,URLSearchParams,window:{location:{href:"http://localhost:5500/app.html",protocol:"http:",search:"",hash:""},history:{replaceState(){}},supabase:{createClient:()=>client}},console,alert(){},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);

let emailError=false;let resetError=false;let requests=0;client.auth.resetPasswordForEmail=async(email,options)=>{requests++;calls.push({recovery:email,options});return {error:emailError?{message:'Rate limited'}:null}};client.auth.updateUser=async payload=>{calls.push({reset:payload});return {error:resetError?{message:'Password rejected'}:null}};client.auth.signOut=async()=>{calls.push({signout:true});return {error:null}};
(async()=>{
await Promise.resolve();els.recoveryEmail.value='student@example.com';await els.forgotPasswordForm.handlers.submit[0]({preventDefault(){}});assert.equal(calls.findLast(c=>c.recovery).options.redirectTo,'http://localhost:5500/app.html?recovery=1');assert(els.recoveryMessage.textContent.includes('If an account exists'));emailError=true;await els.forgotPasswordForm.handlers.submit[0]({preventDefault(){}});assert(els.recoveryError.textContent.includes('Rate limited'));assert(!els.sendRecoveryBtn.disabled);
ctx.window.location.protocol='file:';const count=requests;await els.forgotPasswordForm.handlers.submit[0]({preventDefault(){}});assert.equal(requests,count);assert(els.recoveryError.textContent.includes('website address'));
els.resetPass.value='Newpassword123';els.resetConfirmPass.value='Newpassword123';await els.resetPasswordForm.handlers.submit[0]({preventDefault(){}});assert(els.resetPasswordError.textContent.includes('invalid or expired'));assert(!calls.some(c=>c.reset));
authListener('PASSWORD_RECOVERY',{user:{id:'student1'}});assert(!els.resetPasswordView.classList.contains('hidden'));assert(els.app.classList.contains('hidden'));client.auth.getSession=async()=>({data:{session:{user:{id:'student1'}}},error:null});els.resetConfirmPass.value='Different';await els.resetPasswordForm.handlers.submit[0]({preventDefault(){}});assert(els.resetPasswordError.textContent.includes('do not match'));assert(!calls.some(c=>c.reset));
els.resetConfirmPass.value='Newpassword123';resetError=true;await els.resetPasswordForm.handlers.submit[0]({preventDefault(){}});assert(els.resetPasswordError.textContent.includes('Password rejected'));assert(!els.saveNewPasswordBtn.disabled);resetError=false;await els.resetPasswordForm.handlers.submit[0]({preventDefault(){}});assert.equal(calls.findLast(c=>c.reset).reset.password,'Newpassword123');assert(calls.some(c=>c.signout));assert.equal(run('recoveryMode'),false);assert(!els.loginView.classList.contains('hidden'));assert(els.loginMessage.textContent.includes('Password updated'));
console.log('PASS: recovery redirect, neutral confirmation, rate-limit errors, file-URL prevention, recovery session gate, password match, reset failure, and successful reset/signout.');
})().catch(e=>{console.error(e);process.exitCode=1});