
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'app.html'),'utf8');
const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);
const els={};
function element(id) { const classes=new Set(); const e={value:'',textContent:'',disabled:false,open:false,isConnected:true,handlers:{},dataset:{},selectedOptions:[{textContent:'Fees & payments'}],classList:{toggle(c,on){on?classes.add(c):classes.delete(c)},contains:c=>classes.has(c),add:c=>classes.add(c),remove:c=>classes.delete(c)},addEventListener(t,fn){(this.handlers[t] ||= []).push(fn)},focus(){},showModal(){this.open=true},close(){this.open=false},checkValidity(){return true},reportValidity(){return true},reset(){},querySelector(){return null}};let inner='';Object.defineProperty(e,'innerHTML',{get:()=>inner,set(s){inner=s;if(id==='requestFields')for(const m of s.matchAll(/id="(request_[^"]+)"/g))els[m[1]]=element(m[1]);if(id==='issueType')e.value=''}});return e; }
ids.forEach(id=>els[id]=element(id));
els.staffForm.querySelector=()=>element("staffSubmit");
const profiles=[{id:'it1',full_name:'IT Staff',role:'staff',department:'it'},{id:'finance1',full_name:'Finance Staff',role:'staff',department:'finance'},{id:'admin1',full_name:'Administrator',role:'admin',department:null}];
const rows=[{id:1,subject:'IT request',description:'Original',category:'Account',department:'it',student_id:'s1',status:'Open',created_at:'2026-01-01',assigned_to:null},{id:2,subject:'Finance request',description:'Original',category:'Other',department:'finance',student_id:'s2',status:'Open',created_at:'2026-01-02',assigned_to:null}];
let failProfileUpdate=false;const calls=[];function query(table){const call={table,filters:[]};calls.push(call);const q={select(){return q},eq(k,v){call.filters.push([k,v]);return q},in(){return q},order(){return q},insert(p){call.insert=p;return q},update(p){call.update=p;return q},then(resolve,reject){return Promise.resolve({data:table==='profiles'?profiles:table==='tickets'?rows:[],error:failProfileUpdate&&call.update?{message:"Test save error"}:null}).then(resolve,reject)}};return q;}
const client={functions:{invoke:async(name,options)=>{calls.push({function:name,body:options.body});return {data:{id:"new-staff"},error:null}}},from:query,auth:{getSession:async()=>({data:{}}),signUp:async()=>({data:{user:{id:'new-staff'}},error:null})}};
const ctx={document:{getElementById:id=>els[id]||null,querySelectorAll:()=>[],activeElement:{focus(){},isConnected:true}},window:{supabase:{createClient:()=>client}},console,alert(){},confirm:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
const pending=[];let profileError=false;let emailError=false;client.auth.updateUser=async payload=>{calls.push({emailChange:payload});return {data:{user:{email:'original@example.com'}},error:emailError?{message:'Email unavailable'}:null}};
client.from=table=>{if(table==='ticket_comments'){const c={table};calls.push(c);const q={select(){return q},eq(k,v){c[k]=v;return q},order(){return q},insert(p){c.insert=p;return q},then(resolve,reject){return new Promise((res,rej)=>pending.push({c,resolve:res,reject:rej})).then(resolve,reject)}};return q;}if(table==='profiles'){const c={table};calls.push(c);const q={update(p){c.update=p;return q},eq(){return q},select(){return q},then(resolve,reject){return Promise.resolve({data:[{full_name:c.update.full_name}],error:profileError?{message:'Save failed'}:null}).then(resolve,reject)}};return q;}return query(table);};
const tick=()=>new Promise(r=>setImmediate(r));
const response=message=>({data:[{message,created_at:'2026-10-03',author:{full_name:'Staff',role:'staff'}}],error:null});
(async()=>{
run('currentUser={id:"s1",role:"student",email:"original@example.com",full_name:"Old"};currentTicket={id:1,status:"Open"}');const old=run('loadComments(1)');await tick();run('currentTicket={id:2,status:"Open"}');const latest=run('loadComments(2)');await tick();pending[1].resolve(response('Second ticket'));await latest;pending[0].resolve(response('Wrong ticket'));await old;assert(els.commentList.innerHTML.includes('Second ticket'));assert(!els.commentList.innerHTML.includes('Wrong ticket'));
const fail=run('loadComments(2)');await tick();pending[2].reject(new Error('Network error'));await fail;assert(els.commentList.innerHTML.includes('Network error'));
const sameOld=run('loadComments(2)');const sameNew=run('loadComments(2)');await tick();pending[4].resolve(response('Latest replies'));await sameNew;pending[3].resolve(response('Stale replies'));await sameOld;assert(!els.commentList.innerHTML.includes('Stale replies'));
els.commentText.value='One reply';const submit=()=>els.commentForm.handlers.submit[0]({preventDefault(){}});const send=submit();await tick();await submit();assert.equal(calls.filter(c=>c.insert).length,1);assert(els.sendReplyBtn.disabled);assert(els.commentText.disabled);run('currentTicket={id:3,status:"Open"}');els.commentText.value='New ticket draft';pending[5].resolve({error:null});await send;assert.equal(els.commentText.value,'New ticket draft');assert(!els.sendReplyBtn.disabled);
const errorSend=submit();await tick();pending[6].resolve({error:{message:'Try again'}});await errorSend;assert(els.replyError.textContent.includes('Try again'));assert.equal(els.commentText.value,'New ticket draft');
run('currentTicket={id:4,status:"Closed"}');const count=calls.length;await submit();assert.equal(calls.length,count);
els.profileName.value='Saved name';els.profileEmail.value='original@example.com';await els.saveProfile.handlers.click[0]();assert.equal(run('currentUser.full_name'),'Saved name');assert.equal(els.userName.textContent,'Saved name');assert.equal(calls.findLast(c=>c.table==='profiles').update.full_name,'Saved name');assert.equal(els.profileMessage.textContent,'Profile saved.');
els.profileEmail.value='new@example.com';await els.saveProfile.handlers.click[0]();assert.equal(run('currentUser.email'),'original@example.com');assert(els.profileMessage.textContent.includes('confirmation'));assert.equal(calls.findLast(c=>c.emailChange).emailChange.email,'new@example.com');
emailError=true;els.profileEmail.value='another@example.com';await els.saveProfile.handlers.click[0]();assert(els.profileMessage.textContent.includes('Name saved, but'));assert(!els.saveProfile.disabled);emailError=false;profileError=true;els.profileName.value='Unsaved';await els.saveProfile.handlers.click[0]();assert.equal(run('currentUser.full_name'),'Saved name');assert(els.profileMessage.textContent.includes('Could not save'));
assert(!html.match(/<select id="detailStatus">[\s\S]*?<\/select>/)[0].includes('Closed'));
console.log('PASS: cross-ticket and same-ticket reply races, network errors, duplicate sends, draft preservation, historical reply guard, persisted names, pending email changes, and partial failures.');
})().catch(e=>{console.error(e);process.exitCode=1});